version: "3.8"

services:
  pg_db:
    image: postgres:14-alpine
    container_name: jump_pg_container
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_db:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - jump-net

  server:
    build:
      context: ./server
    image: jump_server_image
    container_name: jump_server_container
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - pg_db
    environment:
      - MODE=${MODE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - API_PORT=${API_PORT}
    networks:
      - jump-net

volumes:
  pg_db:

networks:
  jump-net:
    driver: bridge
